# Model
model_name_or_path: /fsx/vb/new-oai/gpt-oss-20b-trfs-latest
attn_implementation: eager
torch_dtype: bfloat16

# Dataset
dataset_name: HuggingFaceH4/Multilingual-Thinking
dataset_num_proc: 12

# Hyperparameters
learning_rate: 2.0e-4
gradient_checkpointing: true
num_train_epochs: 1.0
logging_steps: 1
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
use_peft: true
lora_r: 2
lora_alpha: 4
lora_dropout: 0.0
lora_target_parameters:
- mlp.experts.down_proj
- mlp.experts.gate_up_proj
max_length: 4096
warmup_ratio: 0.03
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
output_dir: gpt-oss-20b-multilingual-reasoner
report_to:
- trackio
seed: 42